### ISSUE TITLE
Empty configuration in TYPO3 v9

### ISSUE THREAD

**Issue by xperseguers** [xperseguers/t3ext-image_autoresize#18]
Configuration was previously written to `$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['image_autoresize_ff']`. Problem is that in TYPO3 v9, whenever you go to Admin Tools > Settings and try to configure (other) extensions, this automatically cleans up what seems to be useless extension configuration and thus destroys the previously saved configuration for this extension.

**Comment by Patta** [comment]
FYI: https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html

**Comment by fnagel** [comment]
An upgrade guide / a warning would have been helpful for this change...

**Comment by xperseguers** [comment]
A warning? where? it’s supposed to migrate silently

**Comment by fnagel** [comment]
Probably an issue due to using a deployment system? Maybe the new config file was written on the fly but missing with the next deploy?`

**Comment by webian** [comment]
@xperseguers it doesn't seem to migrate silently. I'm using TYPO3 8.7 and https://github.com/xperseguers/t3ext-image_autoresize/blob/076975ed370b38fcfcadf10e3d186d9c93aa80b4/Classes/Controller/ConfigurationController.php#L85 is never called.

**Comment by webian** [comment]
...maybe because ConfigurationController is never instantiated.

**Comment by infabo** [comment]
>  it’s supposed to migrate silently

Silently migrating from `$GLOBALS[‘TYPO3_CONF_VARS’][‘EXT’][‘extConf’]` to some custom php-file-format in `typo3conf`. I mean - wtf? TYPO3 9+ now offers an Extensionconfiguration-API and instead of using it you just introduced a own config-file. Didn't realized until today that this was "broken" for about 3/4 year now cause the "silent migraiton" is only triggered on a setting-change or at least when you call the settings-page. if you dont do that it will work with the defaults.
