### ISSUE TITLE
Image auto rotation - GraphicsMagick (one more time)

### ISSUE THREAD

**Issue by zelcode** [xperseguers/t3ext-image_autoresize#32]
Hi,

can anyone confirm working situation with GraphicsMagick, on one site I had my hack implemented (#23) with version 1.9.1, after updating to 1.9.2 auto rotation doesn't work again.

As I see on file upload, original image is 90 CCW, after upload image is 90 CW.

Thanks.

**Comment by xperseguers** [comment]
OK. I can reproduce. I am on TYPO3 v10 with two images, one 90 CCW the other 90 CW and they are respectively wrongly returned. The problem is indeed related to the explanation in #23 as TYPO3 v9 (and v10) is added the `-auto-orient` parameter, regardless of what we specify. Here is what is finally executed:

```
-auto-orient -geometry 800x1200! -colorspace RGB -quality 85 -rotate 270 
```

I suspect that `-auto-orient` AND `-rotate 270` is a bit too much :)

Indeed, so I can remove this command for GM altogether. Without my extension doing its job, it works automatically.
