### ISSUE TITLE
Frontend-Upload not possible

### ISSUE THREAD

**Issue by kurtzaugg** [xperseguers/t3ext-image_autoresize#35]
Hi, 
after updating the the extension to the latest version and uploading a file in frontend the following (new) error message appears: 
TypeError
Return value of Causal\ImageAutoresize\Slots\FileUpload::getBackendUser() must be an instance of TYPO3\CMS\Core\Authentication\BackendUserAuthentication, null returned.

Thanks for fixing

**Comment by sgrossberndt** [comment]
This happened due to change https://github.com/xperseguers/t3ext-image_autoresize/commit/0d554239bef6cf07971cf84e5fdcc44bf0c378c1 which enforces several `getBackendUser()` methods to return an object of type `BackendUserAuthentication` and does not allow `NULL` but obviously in most cases there is no authenticated backend user available in frontend context (only of an authenticated backend user accesses the frontend). Either the return type enforcement for `BackendUserAuthentication` needs to be reverted or [Nullable types](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types) have to be used.

**Comment by xperseguers** [comment]
The change 0d55423 is relatively big, dare to either suggest a PR or explain more precisely where the nullable type should be added?

**Comment by sgrossberndt** [comment]
As I wrote the problem are all places where `BackendUserAuthentication` is used as a return type without declaring it as nullable. In frontend (if no backend user is logged in) there is no such object so `getBackendUser` will return `NULL`. Each of those methods

`protected function getBackendUser(): BackendUserAuthentication`

must be changed to

`protected function getBackendUser(): ?BackendUserAuthentication`

You are using nullable return types in other places already:
https://github.com/xperseguers/t3ext-image_autoresize/blob/50cd0ae4fd6a5070eb4eb6862328844d3334b03a/Classes/Service/ImageResizer.php#L428

**Comment by sgrossberndt** [comment]
Thanks for fixing it. Could you please create a release for this?
