### ISSUE TITLE
Rule doesnt work, or my configuration is wrong?!

### ISSUE THREAD

**Issue by SteinbachToM** [xperseguers/t3ext-image_autoresize#59]
![Screenshot 2022-01-18 at 13 09 08](https://user-images.githubusercontent.com/95431759/149934889-ff59b6fa-b1c6-473c-ac9d-cb8654339f4a.png)
![Screenshot 2022-01-18 at 13 09 19](https://user-images.githubusercontent.com/95431759/149934894-298bb419-4c2f-4fd8-bd00-3b725e3193ab.png)

the file in the folder and its sub-folders fileadmin/presse_service/Presse/ gets always resized. 
I tried an image with just 1.5MB. Allowed is 8MB.

Any idea what is running wrong?

**Comment by xperseguers** [comment]
No, no idea just like that. You should explain which version you are using.

Apart from that, I think for quite some time that a "debug" mode could be useful in situations like yours. Having a log that describes which tests have been done prior to resizing, which rules have been considered or skipped and why would certainly help users. Otherwise, the only way is reproducing and debugging to understand what happens exactly in a given context.

**Comment by SteinbachToM** [comment]
HI,
TYPO3 10.4.21 and the resize ext ist 2.2.1

**Comment by xperseguers** [comment]
related to #51

What it looks like is that having a large file threshold for a rule makes the rule "not apply" and thus is skipped and then falls back to the default settings which are "lower".
