### ISSUE TITLE
Override the default Configuration in version 2.2.0 with TYPO3 12

### ISSUE THREAD

**Issue by bh-teufels** [xperseguers/t3ext-image_autoresize#79]
how is it possible to define a own 'default' configuration with version 2.2.0 in TYPO3 12 since the procedure from the documentation in Typo3 12 no longer works because the SignalSlot Dispatcher has been removed. 
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/SignalsSlots/Index.html

**Comment by xperseguers** [comment]
The doc is not up-to-date, that's correct, but there's everything in place with the (new) event dispatcher that is available since TYPO3 v10. See corresponding code: https://github.com/xperseguers/t3ext-image_autoresize/blob/master/Classes/Controller/ConfigurationController.php#L425-L435

See Core documentation on how to use: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/EventDispatcher/Index.html
